In [1]:
import numpy as np

# Numpy functions

arange syntax of np.arange()

# np.arange(start,stop,step, dtype)
note: the syntax above, the first three parameters are used to determine the range of the value while the 4th parameter is used to specify the type of the element

In [2]:
ten = np.arange(start = 5,stop = 15, step = 3)
print(ten)

[ 5  8 11 14]


In [3]:
mm = np.arange(5,15,3)
print(mm)

[ 5  8 11 14]


In [4]:
fen = np.arange(start = 10,stop = 30)
print(fen)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [5]:
gg = np.arange(10,30)
print(gg)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [6]:
# nr = np.arange(start = 10)
# nr

# reshape()function

the word reshape simply indicates changing the shape
syntax of reshape is np.reshape(array,newshape,order = "c")


# syntax of reshape: np.reshape(array,newshape,order = "c")

array:This is the array to be reshaped

newshape:The newshape parameter should provide a shape which is compactible with the original shape
    if the value of this parameter is an integer value, then the result will be one dim array

order:This is very important bcos it is used to read the element of the source array and then place the element into the reshaped array

The index order "C" means to read/write the element which C-like index order(and where the last axis index is changing fast back to the first index changing slowly)

The index order "F" means to read/write the element which are using the fortran-like index order(and where the last axis index is changing slow, the firstaxis index is changing fast)opp of C

A order simply means to read/write the element in a fortran-like index order only when the array to be shaped is contagious in memory otherwise use a C-like index order

In [7]:
tell = np.arange(40)
print(tell)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [8]:
fed =np.arange(20).reshape(4,5)
print(fed)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [9]:
# nn = tell.reshape(4,5)
# print(nn)

In [10]:
nn = tell.reshape(2,5,4)
nn

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [11]:
cell = np.arange(20)
print(cell)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
zz = cell.reshape(1,5,4)
zz

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [13]:
cell = np.arange(20)
cell2 = np.reshape(cell,(4,5),order = "F")
print(cell2)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [14]:
ven = np.arange(20)
ven2 = np.reshape(ven,(4,5),order = "C")
print(ven2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# Append()

syntax = np.append(array,values,axis = None)
parameters:
    
array:This represents the ndarray to which the new values will be appended and new array will be created
values:This is purposely used to define the values that are needed to append a copy of a (the existing ndarray), note: the values must be of the correct shape(the original ndarray)
axis: This is optional, it is used to define the axis along which the values are appended. when the axis is not given then both ndarray and values are flattened before use        

In [15]:
red = np.array([[2,5,6],[7,8,9]])
met = np.array([[3,4,5],[1,2,6]])
print(red,"\n")
print(met)

[[2 5 6]
 [7 8 9]] 

[[3 4 5]
 [1 2 6]]


In [16]:
yy = np.append(red,met,axis = 0)
print(yy)

[[2 5 6]
 [7 8 9]
 [3 4 5]
 [1 2 6]]


In [17]:
yy = np.append(red,met,axis = 1)
print(yy)

[[2 5 6 3 4 5]
 [7 8 9 1 2 6]]


# Concatenate()

syntax = np.concatenate((array,array1,...), axis = 0, out = None)

parameters:
(array,array1,...): This represents the sequence of array-like structure. these arrays should have thesame shape b4 they can be concatenated
axis:This is used to define the axis along which the array should be concatenated. the default value is 0
out: This is optional but it is provided when destination of the result placed, if there is no out parameter specified then the shape must be correct to match

In [18]:
pp = np.array([[4,6,8],[9,3,6]])
mm = np.array([[8,4,3],[6,7,5]])
print(pp,"\n \n",mm)


[[4 6 8]
 [9 3 6]] 
 
 [[8 4 3]
 [6 7 5]]


In [19]:
ss = np.concatenate((pp,mm), axis = 0, out = None)
print(ss)

[[4 6 8]
 [9 3 6]
 [8 4 3]
 [6 7 5]]


In [20]:
tt = np.concatenate((pp,mm), axis = 1, out = None)
print(tt)

[[4 6 8 8 4 3]
 [9 3 6 6 7 5]]


# array() function

In numpy large or multidimensional array is the main objective. this multidimensional array is basically a table of element and this element are all of thesame type and indexed by a tuple of positive integers.
note: dimensions of an array are called axis in numpy. the array class in numpy library is mainly known as ndarray or array

syntax = np.array(object,copy = True, dtype = None, order = "K", subok = False, ndmin = 0)

In [21]:
yes = np.array([1,2,3,4,5])
yes

array([1, 2, 3, 4, 5])

In [22]:
met = np.array([[3,4,5],[1,2,6]])

In [23]:
yes = np.array([1,2,3,4,5], dtype = "complex")
yes

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

# Transpose() function

Transpose() is mainly used reverse or permute the axis of an array(the main function of this is to change the column element into row element and vice versa)
note: transpose has no effect on 1-D array, it is used for 2-D or more arrays.

syntax:np.transpose(array,axis = None)
parameters:
array:this is the array to be changed 
axis:this is an optional element but if value is passed then know it should pass(0,1)or(1,0). like we have array of shape(4,3) to change into (3,4), we should pass(1,0) where 1 represent 4 and 0 represent 3

In [24]:
hh = np.array([[5,7,8],[9,10,11],[12,13,14]])
print(hh)

[[ 5  7  8]
 [ 9 10 11]
 [12 13 14]]


In [25]:
pp = np.transpose(hh)
print(pp)

[[ 5  9 12]
 [ 7 10 13]
 [ 8 11 14]]


In [26]:
pp = np.transpose(hh,(1,0))
print(pp)

[[ 5  9 12]
 [ 7 10 13]
 [ 8 11 14]]


In [27]:
pp = np.transpose(hh,(0,1))
print(pp)

[[ 5  7  8]
 [ 9 10 11]
 [12 13 14]]


# partition() function

syntax = np.partition(array,kth,axis,kind,order)

In [28]:
gas = np.array([2,0,1,6,4,13,70,90,])
why = np.partition(gas,4)
print(why)

[ 4  2  1  0  6 13 70 90]


In [29]:
find = np.array([4,5,6,3,60,50,100,200])
you = np.partition(find,(3,4))
print(you)

[  3   4   5   6  50  60 100 200]


# Numpy mathematical functions

# CEIL() function

Ceil() function is used to return the ceil of the elements of an array. the ceil value of x is the smallest int i in a way such that i>=x. eg 7.8, the ceil value will be 8 ie the nearest largest integer value is the ceil value

syntax = np.ceil(array)

In [30]:
price = np.array([5.9,3.4,2.2,4.8,6.3,7.6,9.1,11.0])
new_price = np.ceil(price)
print(new_price)

[ 6.  4.  3.  5.  7.  8. 10. 11.]


In [31]:
new_values = np.array([-2.2,-4.4,-5.5,-7.7])
second_price = np.ceil(new_values)
print(second_price)

[-2. -4. -5. -7.]


# Floor() function

floor() function is used to return the floor of the elements of an array. the floor value of x is the smallest int i in a way such that i<=x. eg 7.8, the floor value will be 7 ie the nearest lowest integer value is the floor value

syntax = np.floor(array)

In [32]:
score = np.array([59.2,40.0,99.9,87.5,93.2])
llist = np.floor(score)
print(llist)

[59. 40. 99. 87. 93.]


In [33]:
one = np.array([1.2,-3.5,4.5,-6.7,-5.9])
two = np.floor(one)
print(two)

[ 1. -4.  4. -7. -6.]


# Truncate() function

Truncate() function is used to return the truncated value of the array. note: the truncated value x of the array y should be the nearest integer which is closer to zero rather than the y

syntax = np.trunc(array)

In [34]:
key = np.array([1.2,-1.3,2.1,-2.2,3.1,-3.4])
main = np.trunc(key)
print(main)

[ 1. -1.  2. -2.  3. -3.]


# Fix() function

Fix() function is used to round the array values to the nearest integers towards zero

syntax = np.fix(array,b = None)

parameters:
array: represents the array whose elements are to be worked on
b: it is used to provide an ndarray which represents the location into which the result will be stored
 note: the b is optional

In [35]:
red = [0.89,0.45,1.67,4.78,8.19,9.09]
good = np.fix(red)
print(good)

[0. 0. 1. 4. 8. 9.]


# Statistical functions

# amin() function

amin() function: is used to return the minimum element of an array or minimum element along an axis 

syntax = np.amin(array,axis,out,keepdims = , initial = , where = )

parameters:
array: the array indicates the input data
axis: this represents the axis along which we operate(optional)
out: this is used to indicate an alternative output array in which result get stored.
keepdims:this is used to broadcast the result correctly against the input array, if it is set to true, the axis which are reduced are left in the result as dimension with size one(it is optional with a boolean value)
initial:this is the scalar and is used to indicate max value of an output element
where:it is an optional value used to indicate the element to compare for the minimum value

In [36]:
you = np.array([[5,10,15],[20,25,30],[2,4,3]])
print(you)

[[ 5 10 15]
 [20 25 30]
 [ 2  4  3]]


In [37]:
print(np.amin(you))
print(np.amin(you,0))
print(np.amin(you,1))

2
[2 4 3]
[ 5 20  2]


In [38]:
print(np.amin(you))
print(np.amin(you,axis = 0))
print(np.amin(you,axis = 1))

2
[2 4 3]
[ 5 20  2]


In [39]:
# print(np.amin(you,where = [True,False], initial = 10, axis = 0))

# amax() function

syntax = np.amax(array,axis,out,keepdims =<no value> , initial =<no value>, where = )

In [40]:
my = np.array([[5,10,15],[20,25,30],[2,4,3]])
print(my)

[[ 5 10 15]
 [20 25 30]
 [ 2  4  3]]


In [41]:
print(np.amax(my))
print(np.amax(my,0))
print(np.amax(my,1))

30
[20 25 30]
[15 30  4]


In [42]:
print(np.amax(my))
print(np.amax(my,axis = 0))
print(np.amax(my,axis = 1))

30
[20 25 30]
[15 30  4]


# ptp() function

syntax = np.ptp(array,axis = None, out = None, keepdims =<no value>)
ptp stands for peak to peak

In [43]:
pen = np.array([1,2,5,np.nan])
print(pen)

[ 1.  2.  5. nan]


In [44]:
print(np.ptp(pen))

nan


In [45]:
seq = np.array([[4,5,6],[6,7,8],[9,10,11]])
print(seq)
print(np.ptp(seq))

[[ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]
7


In [46]:
seq = np.array([[4,5,6,7],[6,7,8,4],[9,10,11,2]])

In [47]:
print(seq)

[[ 4  5  6  7]
 [ 6  7  8  4]
 [ 9 10 11  2]]


In [48]:
print(np.ptp(seq))

9


In [49]:

print(np.ptp(seq,axis = 0))

[5 5 5 5]


In [50]:
print(np.ptp(seq,axis = 1))

[3 4 9]


# median() function

syntax = np.median(array,axis = None, out, dtype)

it is used to calculate the median along any specified axis, 
the median returns the median of the array element 

In [51]:
tell = [10,52,73,24,45]
print(np.median(tell))

45.0


In [52]:
dell = np.array([[10,25,35],[5,40,50],[20,55,60]])
print(np.median(dell))

35.0


In [53]:
print(dell)

[[10 25 35]
 [ 5 40 50]
 [20 55 60]]


In [64]:
print(np.median(dell,axis = 0))
print(np.median(dell,axis = 1))

[10. 40. 50.]
[25. 40. 55.]


# mean() function

syntax = np.median(array,axis = None, out, dtype)

In [55]:
tt = np.array([2,3,4,5])
print(np.mean(tt))

3.5


In [56]:
ss = np.array([[4,3,2],[6,7,8],[1,9,8]])
print(np.mean(ss))

5.333333333333333


In [57]:
print(ss)

[[4 3 2]
 [6 7 8]
 [1 9 8]]


In [58]:
print(np.mean(ss,axis = 0))
print(np.mean(ss,axis = 1))

[3.66666667 6.33333333 6.        ]
[3. 7. 6.]


# std() function

syntax = np.median(array,axis = None, out, dtype)
std stands for standard deviation

In [59]:
kk = np.array([1,4,5])
print(np.std(kk))

1.699673171197595


In [60]:
pp = np.array([[5,10,15],[20,30,40]])
print(np.std(pp))

11.902380714238083


In [61]:
print(pp)

[[ 5 10 15]
 [20 30 40]]


In [65]:
print(np.std(pp,axis = 0))
print(np.std(pp,axis = 1))

[ 7.5 10.  12.5]
[4.0824829  8.16496581]
