In [2]:
import numpy as np
array = np.arange(10)
squared_array = array ** 2
print(squared_array)


[ 0  1  4  9 16 25 36 49 64 81]


In [6]:
import numpy as np
a = np.arange(start=0, stop=6, step=1)
a2 = a[np.newaxis, :]
a2.shape
(1, 6)

(1, 6)

In [8]:
import numpy as np
makky = np.arange(10)
squared_makky = makky ** 2
print(squared_makky)

[ 0  1  4  9 16 25 36 49 64 81]


In [9]:
# creating array object

In [61]:
arr = np.array([[1,2,3,6],[4,2,5,4]])

In [56]:
# printing type of arr object

In [57]:
print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [58]:
type(arr)

numpy.ndarray

In [59]:
# printing array dimensions (axes)

In [60]:
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


In [18]:
# printing shape of array

In [62]:
print("shape of array: ", arr.shape)

shape of array:  (2, 4)


In [21]:
# printing size (total number of elements) of array

In [63]:
print("size of array: ", arr.size)

size of array:  8


In [24]:
# printing type of elements in array

In [27]:
print("Array stores elements of type: ", arr.dtype)

Array stores elements of type:  int32


# NUMPY ARRAY CREATION

There are various ways of numpy array creation in python. they are as follows:
1. you can create an array from a regular python list or tuple using the array() function.
the type of the resulting array is deduced from the type of the elements in the sequence. lets see this implementation:

In [28]:
# creating array from list with type float

In [30]:
a = np.array([[1,2,4], [5,8,7]], dtype = 'float')
print("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [31]:
# creating array from tuple

In [33]:
b = np.array((1,3,2))
print("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


2. often, the elements is of an array is originally unknown, but its size is known. Hence, numpy offers several functions to create arrays with initial placeholder content. these minimize the necessity of growing arrays, an expensive operation. for example: np.zeros, np.ones, np.full, np.empty, etc.
To create sequence of numbers, numpy provides a function anologues to the range that returns arrays instead of lists

In [34]:
# creating a 3x4 array with all zeros

In [36]:
c = np.zeros((3,4))
print("An array initialized with all zeros:\n", c)

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
# create a constant value array of complex type

In [68]:
d = np.full((3,3), 6, dtype = 'complex')
print("An array initialized with all 6s."
     "Array type is complex:\n", d)

An array initialized with all 6s.Array type is coplex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [67]:
# create an array with random values

In [71]:
e = np.random.random((2,2))
print("A random array:\n", e)

A random array:
 [[0.09709104 0.83574111]
 [0.38465539 0.19235726]]


3. arange: This function returns evenly spaced values within a given interval. step size is specified.

In [43]:
# create a sequence of integers
# from 0 to 30 with steps of 5

In [45]:
f = np.arange(0, 30, 5)
print("A sequential array with steps of 5:\n", f)

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


4. linspace: It returns evenly spaced values within a given interval.

In [47]:
# create a sequence of 10 values in range 0 to 5

In [72]:
g = np.linspace(0, 15, 20)
print("A sequential array with 10 values between"
     "0 and 5:\n",)
print(g)

A sequential array with 10 values between0 and 5:

[ 0.          0.78947368  1.57894737  2.36842105  3.15789474  3.94736842
  4.73684211  5.52631579  6.31578947  7.10526316  7.89473684  8.68421053
  9.47368421 10.26315789 11.05263158 11.84210526 12.63157895 13.42105263
 14.21052632 15.        ]
