# Data types in numpy

i = int
f = float
b = boolean
u = unsigned integer
c = complex float
m = timedelta
M = datetime
O = object
S = string
U = unicode
V = void


In [2]:
import numpy as np

In [3]:

arr = np.array(["python", "django", "numpy", "java", "html", "css"])
print(arr.dtype)

<U6


In [4]:
name = np.dtype(np.int64)
print(name)
red = np.array([5,6,7])
print(red.dtype)

int64
int32


In [5]:
blue = np.array([5.3,8.9,7.6])
print(blue.dtype)

float64


In [6]:
orange = np.dtype("i4")
print(orange)

int32


In [7]:
mean = np.dtype([("fruits",np.int64 )])
print(mean)

[('fruits', '<i8')]


In [8]:
mean

dtype([('fruits', '<i8')])

# How to change the data type

In [9]:
car = np.array([1.1, 1.5, 2.2, 6.7])
print(car.dtype)

float64


In [10]:
moon = car.astype(int)
print(moon.dtype)

int32


In [11]:
print(moon)

[1 1 2 6]


# Creating empty array

In [12]:
done = np.empty([6,8], dtype=float)
print(done)

[[7.79293458e-312 7.79255178e-312 4.27255707e+180 6.96771801e+252
  7.08468655e+159 8.12555790e-096 1.12958007e+277 9.60674952e-037]
 [7.01413727e-009 6.97387871e+228 7.47011456e-114 5.95750259e+271
  5.95915351e+271 5.43256360e-096 1.06259729e+223 1.14489505e-095]
 [7.16006779e-062 9.13544126e+242 1.05135744e-153 2.00007403e+174
  7.36191050e+223 1.05164869e-153 8.95402175e-096 6.82996787e-307]
 [7.79295370e-312 7.79271812e-312 4.56340406e-072 6.82997463e-307
  7.79293265e-312 7.79257220e-312 7.49744161e+247 1.05161990e-153]
 [7.13637443e+159 1.35717430e+131 8.65810414e+140 6.01347002e-154
  6.96320207e-077 6.01347002e-154 6.03104724e-154 7.04134408e-009]
 [6.21834938e+175 5.22936920e-067 4.83245960e+276 6.03104753e-154
  6.01346953e-154 1.05133138e-153 6.01334510e-154 8.01802173e-096]]


# To check zeros

In [13]:
good = np.zeros([10,5], dtype = float)
print(good)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
bad = np.ones((5,10), dtype = str)
print(bad)

[['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']]


# Creating array using existing data

In [15]:
undo = (20,40,50,60)
you = np.asarray(undo)
print(you)
print(type(you))

[20 40 50 60]
<class 'numpy.ndarray'>


# 2 dimensional array

In [16]:
source = [[1,2,3], [4,5,6]]
son = np.asarray(source)
print(son)
print(type(son))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


# Creating arrays with frombuffer

In [17]:
house_man = b"wearelearningnumpy"
print(type(house_man))

<class 'bytes'>


In [18]:
new = np.frombuffer(house_man, dtype = "S1")
print(new)
print(type(new))

[b'w' b'e' b'a' b'r' b'e' b'l' b'e' b'a' b'r' b'n' b'i' b'n' b'g' b'n'
 b'u' b'm' b'p' b'y']
<class 'numpy.ndarray'>


# Creating arrays with iterator

In [25]:
iron = (4,6,7,8)
shoes = iter(iron)
print(type(shoes))
print(shoes)
bags = np.fromiter(shoes, dtype = float)
print(bags)
print(type(bags))



<class 'tuple_iterator'>
[4. 6. 7. 8.]
<class 'numpy.ndarray'>


# Array creation from numerical ranges

In [26]:
sea = np.arange(20)
print(sea)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [34]:
new = np.arange(0, 15, 3, complex)
print(new)


[ 0.+0.j  3.+0.j  6.+0.j  9.+0.j 12.+0.j]


# Array creation using linspace
np.linspace(start, end, space)

In [37]:
house = np.linspace(20, 40, 5)
print(house)

[20. 25. 30. 35. 40.]


In [44]:
hut = np.linspace(5, 20, 3, retstep = True)
print(hut)


(array([ 5. , 12.5, 20. ]), 7.5)


# Array creation using logspace

In [54]:
wheb =np.logspace(3, 15, num = 10)
print(wheb)

[1.00000000e+03 2.15443469e+04 4.64158883e+05 1.00000000e+07
 2.15443469e+08 4.64158883e+09 1.00000000e+11 2.15443469e+12
 4.64158883e+13 1.00000000e+15]


In [55]:
wen = np.logspace(2, 20, num = 8, base = 5, endpoint = True)
print(wen)

[2.50000000e+01 1.56780285e+03 9.83202305e+04 6.16586949e+06
 3.86674709e+08 2.42491884e+10 1.52071786e+12 9.53674316e+13]
