# numpy indexing and slicing

In [49]:
import numpy as np

There are 3 types of indexing
1 field access(this is direct field access using the index of the value)
2 basic slicing
3 advanced slicing

# Field access

In [50]:
courses = ["maths", "agric", "computer", "health"]
print(courses[1])

agric


In [51]:
num = np.arange(16)
print(num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


# basic slicing

In [52]:
number = slice(2, 13, 2)
# print(number)
print(num[number])

[ 2  4  6  8 10 12]


In [53]:
den = num[6]
print(den)

6


In [54]:
fen = np.arange(20)
print(fen)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [55]:
print(fen[8:19])
print(fen[9:])
print(fen[:11])

[ 8  9 10 11 12 13 14 15 16 17 18]
[ 9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10]


# ellipsis(...) can be used for slicing

In [56]:
nrr = np.array([[1,2,3], [3,4,5], [6,7,8]])
# print(nrr.ndim)
print(nrr)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [57]:
print(nrr[..., 1])

[2 4 7]


In [73]:
print(nrr[2,...])

[6 7 8]


In [59]:
print(nrr[0,...])

[1 2 3]


In [60]:
print(nrr[..., 1:]) # slicing all items from column 1 upwards

[[2 3]
 [4 5]
 [7 8]]


# Advanced indexing(slicing)

In [61]:
arr = np.array([[1,2], [3,4], [5,6], [7,8]])
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [62]:
set = arr[[0, 1, 2, 3], [0,0,1,0]]
print(set)

[1 3 6 7]


In [63]:
n1 = np.array([[1], [2], [3]])
n2 = np.array([[2,3], [4,6], [8,9]])
print(n1)
print(n2)

[[1]
 [2]
 [3]]
[[2 3]
 [4 6]
 [8 9]]


In [64]:
# n3 = arr[n1][n2]
# print(n3)

# Boolean indexing

it is a kind of advanced indexing that is used when we want to pick element from ndarray based on some conditions using comparison operators or some other operators

In [65]:
net = np.array([[2,3,4,15], [5,6,7,8], [8,9,10,9]])
print(net)

[[ 2  3  4 15]
 [ 5  6  7  8]
 [ 8  9 10  9]]


In [66]:
some = net[net>=6]
print(some)

[15  6  7  8  8  9 10  9]


# How to remove not a number

In [67]:
one = np.array([5,np.nan,3,np.nan,4,7,8])
one[np.isnan(one)]
# one[np.isnumber(one)]

array([nan, nan])

# How to remove complex numbers

In [68]:
ray = np.array([1,2+6j,7,3.5+7j,3j])
ray[np.iscomplex(ray)]

array([2. +6.j, 3.5+7.j, 0. +3.j])

# Broadcasting
this refers to how numpy handles arrays of differnt dimensions while performing any arithmetical operations. in broadcasting, numpy generally broadcast the small array across the large array in other to have a compactible shape

In [69]:
one = np.array([1,2,3,4,5])
two = np.array([6,7,8,9,10])

In [70]:
three = one + two
print(three)

[ 7  9 11 13 15]


Rules for broadcasting numpy
1 the size of each output dim should be the maximum of the input size in dim
2 the smaller dim ndarray can be appended with value 1 in each shape
3 if the input size is one then the ist data entry should be used for the calculation along the dim

In [71]:
jen = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
ben = np.array([7,8,9,10])

In [72]:
den = jen + ben
print(den)

[[ 8 10 12 14]
 [12 14 16 18]
 [16 18 20 22]]
